-- MySQL Script generated by MySQL Workbench
-- Fri Feb 19 18:49:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fibudb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fibudb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fibudb` DEFAULT CHARACTER SET utf8 ;
USE `fibudb` ;

-- -----------------------------------------------------
-- Table `fibudb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`Class` (
  `classID` INT NOT NULL AUTO_INCREMENT,
  `className` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`classID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `classID` INT NULL,
  PRIMARY KEY (`userID`),
  INDEX `User-Class-FK_idx` (`classID` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `User-Class-FK`
    FOREIGN KEY (`classID`)
    REFERENCES `fibudb`.`Class` (`classID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`Subject` (
  `subjectID` INT NOT NULL AUTO_INCREMENT,
  `subjectName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subjectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`AccountChart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`AccountChart` (
  `accountChartID` INT NOT NULL AUTO_INCREMENT,
  `acName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`accountChartID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`ExerciseGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`ExerciseGroup` (
  `exerciseGroupID` INT NOT NULL AUTO_INCREMENT,
  `exGroupName` VARCHAR(45) NOT NULL,
  `subjectID` INT NOT NULL,
  `accountChartID` INT NOT NULL,
  `questionAmount` INT NOT NULL,
  PRIMARY KEY (`exerciseGroupID`),
  INDEX `ExerciseGroup-Subject-FK_idx` (`subjectID` ASC) VISIBLE,
  INDEX `ExerciseGroup-AccountChart-FK_idx` (`accountChartID` ASC) VISIBLE,
  CONSTRAINT `ExerciseGroup-Subject-FK`
    FOREIGN KEY (`subjectID`)
    REFERENCES `fibudb`.`Subject` (`subjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ExerciseGroup-AccountChart-FK`
    FOREIGN KEY (`accountChartID`)
    REFERENCES `fibudb`.`AccountChart` (`accountChartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`Question` (
  `questionID` INT NOT NULL AUTO_INCREMENT,
  `qNumber` INT NOT NULL,
  `qText` VARCHAR(600) NOT NULL,
  `qDisclaimer` VARCHAR(200) NULL,
  `exerciseGroupID` INT NOT NULL,
  PRIMARY KEY (`questionID`),
  INDEX `Question-ExerciseGroup-FK_idx` (`exerciseGroupID` ASC) VISIBLE,
  CONSTRAINT `Question-ExerciseGroup-FK`
    FOREIGN KEY (`exerciseGroupID`)
    REFERENCES `fibudb`.`ExerciseGroup` (`exerciseGroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`Account` (
  `accountID` INT NOT NULL AUTO_INCREMENT,
  `accountNumber` VARCHAR(45) NULL,
  `accountName` VARCHAR(45) NOT NULL,
  `accountChartID` INT NOT NULL,
  PRIMARY KEY (`accountID`),
  INDEX `Account-AccountChartID-FK_idx` (`accountChartID` ASC) VISIBLE,
  CONSTRAINT `Account-AccountChartID-FK`
    FOREIGN KEY (`accountChartID`)
    REFERENCES `fibudb`.`AccountChart` (`accountChartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`Subquestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`Subquestion` (
  `subquestionID` INT NOT NULL AUTO_INCREMENT,
  `sqText` VARCHAR(200) NOT NULL,
  `sqLetter` VARCHAR(1) NULL,
  `sqType` VARCHAR(45) NOT NULL,
  `questionID` INT NOT NULL,
  PRIMARY KEY (`subquestionID`),
  INDEX `Subquestion-Question-FK_idx` (`questionID` ASC) VISIBLE,
  CONSTRAINT `Subquestion-Question-FK`
    FOREIGN KEY (`questionID`)
    REFERENCES `fibudb`.`Question` (`questionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`MCOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`MCOption` (
  `mcOptionID` INT NOT NULL AUTO_INCREMENT,
  `mcoName` VARCHAR(200) NOT NULL,
  `subquestionID` INT NOT NULL,
  PRIMARY KEY (`mcOptionID`),
  INDEX `MCOption-Subquestion-FK_idx` (`subquestionID` ASC) VISIBLE,
  CONSTRAINT `MCOption-Subquestion-FK`
    FOREIGN KEY (`subquestionID`)
    REFERENCES `fibudb`.`Subquestion` (`subquestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`BookEntry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`BookEntry` (
  `bookEntryID` INT NOT NULL AUTO_INCREMENT,
  `accountSoll` INT NOT NULL,
  `accountHaben` INT NOT NULL,
  `amount` DECIMAL(11,2) NOT NULL,
  `subquestionID` INT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`bookEntryID`),
  INDEX `BookEntry-Subquestion-FK_idx` (`subquestionID` ASC) VISIBLE,
  INDEX `BookEntry-User-FK_idx` (`userID` ASC) VISIBLE,
  INDEX `BookEntrySoll-Account-FK_idx` (`accountSoll` ASC) VISIBLE,
  INDEX `BookEntryHaben-Account-FK_idx` (`accountHaben` ASC) VISIBLE,
  CONSTRAINT `BookEntry-Subquestion-FK`
    FOREIGN KEY (`subquestionID`)
    REFERENCES `fibudb`.`Subquestion` (`subquestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BookEntry-User-FK`
    FOREIGN KEY (`userID`)
    REFERENCES `fibudb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BookEntrySoll-Account-FK`
    FOREIGN KEY (`accountSoll`)
    REFERENCES `fibudb`.`Account` (`accountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BookEntryHaben-Account-FK`
    FOREIGN KEY (`accountHaben`)
    REFERENCES `fibudb`.`Account` (`accountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`MCAnswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`MCAnswer` (
  `mcAnswerID` INT NOT NULL AUTO_INCREMENT,
  `mcOptionID` INT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`mcAnswerID`),
  INDEX `MCAnswer-User-FK_idx` (`userID` ASC) VISIBLE,
  INDEX `MCAnswer-MCOption-FK_idx` (`mcOptionID` ASC) VISIBLE,
  CONSTRAINT `MCAnswer-MCOption-FK`
    FOREIGN KEY (`mcOptionID`)
    REFERENCES `fibudb`.`MCOption` (`mcOptionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MCAnswer-User-FK`
    FOREIGN KEY (`userID`)
    REFERENCES `fibudb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibudb`.`EGResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibudb`.`EGResult` (
  `egResultID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `exerciseGroupID` INT NOT NULL,
  `solved` DECIMAL(3,1) NOT NULL,
  `correct` DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (`egResultID`),
  INDEX `EGResult-User-FK_idx` (`userID` ASC) VISIBLE,
  INDEX `EGResult-ExerciseGroup-FK_idx` (`exerciseGroupID` ASC) VISIBLE,
  CONSTRAINT `EGResult-User-FK`
    FOREIGN KEY (`userID`)
    REFERENCES `fibudb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EGResult-ExerciseGroup-FK`
    FOREIGN KEY (`exerciseGroupID`)
    REFERENCES `fibudb`.`ExerciseGroup` (`exerciseGroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
